### ISSUE TITLE
Pacer needs supportsIndices to be true to use key indices in Titan

### ISSUE THREAD

**Issue by pangloss** [xnlogic/pacer#41]
It should only look at the key indices flag for that.

https://gist.github.com/efi/4994045#file-patched-rb-L29

**Comment by joeyfreund** [comment]
Since Titan is no longer relevant, should we close this issue?

**Comment by mrbotch** [comment]
This issue has been fixed a while ago I think. I'm still using Pacer with Titan 0.5.4 in a production project, from what I understand Titan 1.0 will be using TinkerPop 3 and will continue to be an open-source project despite Aurelius now working with DataStax on a closed-source graph db. The public pacer-titan gem has not been updated to the latest version of Titan because the source has been in so much flux but I'm keen to keep Titan support on board (unless you guys don't want to use TP3 at all when it comes out)
